CREATE TABLE WEB_EVENTS(ID SERIAL PRIMARY KEY,
ACCOUNT_ID INT,
OCCURRED_AT TIMESTAMP,
CHANNEL VARCHAR(255)
);

CREATE TABLE ACCOUNTS(ID SERIAL PRIMARY KEY,
NAME VARCHAR(255),
WEBSITE VARCHAR(255),
LATITUDE DECIMAL (9,6),
LONGITUDE DECIMAL(9,6),
PRIMARY_POC VARCHAR(255),
SALES_REP_ID INT
);

CREATE TABLE ORDERS(ID SERIAL PRIMARY KEY,
ACCOUNT_ID SERIAL,
STANDARD_QUANTITY INT,
POSTER_QUANTITY INT,
TOTAL INT,
GROSS_QUANTITY INT,
STANDARD_AMT_USD DECIMAL(10,2),
GROSS_AMT_USD DECIMAL(10,2),
POSTER_AMT_USD DECIMAL(10,2),
TOTAL_AMT_USD DECIMAL(10,2)
);

CREATE TABLE SALES_REPS(ID SERIAL PRIMARY KEY,
NAME VARCHAR (255),
REGION_ID INT
);

CREATE TABLE REGION(ID SERIAL PRIMARY KEY,
NAME VARCHAR(255)
);

ALTER TABLE WEB_EVENTS ADD FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNTS(ID);
ALTER TABLE ACCOUNTS ADD FOREIGN KEY(SALES_REP_ID) REFERENCES SALES_REPS(ID);
ALTER TABLE ORDERS ADD FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNTS(ID);
ALTER TABLE SALES_REPS ADD FOREIGN KEY(REGION_ID) REFERENCES REGION(ID);